---
name: Linting (Hadolint)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:

  hadolint:
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./Dockerfile
          verbose: true
          format: tty
          # DL3003: Use WORKDIR to switch to a directory
          #   - Ignored because we use pushd/popd to move around the image without creating extra layers.
          # --ignore DL3003 --ignore DL3006 --ignore DL3010 --ignore DL4001 --ignore DL3007 --ignore DL3008 --ignore SC2068 --ignore DL3007 --ignore SC1091 --ignore DL3013 --ignore DL3010
          ignore: DL3003 
